Repository JavierMarrero/jlibgraph, pull requests merged in 2022-11, with the labels that each got.

#19 ExistPath algorithm and GraphBuilders fixed for supporting directed graphs
  src/cu/edu/cujae/graphy/algorithms/ExistPath.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultGraphBuilder.java
  src/cu/edu/cujae/graphy/core/utility/GraphBuilders.java
  test/cu/edu/cujae/graphy/tests/LocalTest.java
  test/cu/edu/cujae/graphy/tests/SimpleGraphTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/ExistPathTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/HamiltonCycleTest.java
Labels: enhancement

#32 Commit to seal development branch.
  src/cu/edu/cujae/graphy/core/Edge.java
  src/cu/edu/cujae/graphy/core/Node.java
  src/cu/edu/cujae/graphy/core/Weight.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractEdge.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultSimpleGraph.java
  test/cu/edu/cujae/graphy/tests/algorithms/DijkstraTest.java
Labels: enhancement

#35 Titulo cool jsjsjs
  lib/nblibraries.properties
  src/cu/edu/cujae/graphy/algorithms/BellmanFordShortestPath.java
  test/cu/edu/cujae/graphy/tests/algorithms/BellmanFordTest.java
Labels: documentation, enhancement, good first issue

#37 Added graph cloning, immutable graphs and new method and constraints
  src/cu/edu/cujae/graphy/algorithms/BellmanFordShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/BridgeFinderAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/DijkstraShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/ExistSimpleRoad.java
  src/cu/edu/cujae/graphy/algorithms/KargerMinimumCut.java
  src/cu/edu/cujae/graphy/algorithms/MotherVertexFind.java
  src/cu/edu/cujae/graphy/core/Edge.java
  src/cu/edu/cujae/graphy/core/Graph.java
  src/cu/edu/cujae/graphy/core/Node.java
  src/cu/edu/cujae/graphy/core/Weight.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractEdge.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractWeight.java
  src/cu/edu/cujae/graphy/core/abstractions/AdjacencyListGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNotDirectedEdgeFactory.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultSimpleGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultWeightedGraph.java
  src/cu/edu/cujae/graphy/core/exceptions/InvalidOperationException.java
  src/cu/edu/cujae/graphy/core/iterators/AbstractGraphIterator.java
  src/cu/edu/cujae/graphy/core/trees/AbstractTreeNode.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTree.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
  src/cu/edu/cujae/graphy/core/utility/Graphs.java
  src/cu/edu/cujae/graphy/utils/MapTriArray.java
  test/cu/edu/cujae/graphy/tests/CloneTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/BellmanFordTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/BridgeFinderTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/DijkstraTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/ShortestPathKEdgeTest.java
Labels: documentation, enhancement, good first issue

#42 Ahora sí.
  lib/nblibraries.properties
  nbproject/project.properties
  src/cu/edu/cujae/graphy/algorithms/AbstractAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/ColorableAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/DialShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/DijkstraShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/ExistSimpleRoad.java
  src/cu/edu/cujae/graphy/algorithms/KosarajuAlgorithm.java
  src/cu/edu/cujae/graphy/core/Edge.java
  src/cu/edu/cujae/graphy/core/Graph.java
  src/cu/edu/cujae/graphy/core/Node.java
  src/cu/edu/cujae/graphy/core/Weight.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractEdge.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractWeight.java
  src/cu/edu/cujae/graphy/core/abstractions/AdjacencyListGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNotDirectedEdgeFactory.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultSimpleGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultWeightedGraph.java
  src/cu/edu/cujae/graphy/core/exceptions/InvalidOperationException.java
  src/cu/edu/cujae/graphy/core/trees/AbstractTreeNode.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTree.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
  src/cu/edu/cujae/graphy/core/utility/Graphs.java
  test/cu/edu/cujae/graphy/tests/CloneTest.java
Labels: documentation, enhancement, good first issue

#44 Added a few more utility functions to the nodes and iterators.
  src/cu/edu/cujae/graphy/core/Node.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/iterators/AbstractGraphIterator.java
  src/cu/edu/cujae/graphy/core/iterators/GraphIterator.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
Labels: enhancement

#51 pequeños avances :D
  nbproject/project.properties
  src/cu/edu/cujae/graphy/algorithms/ColorableAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/DialShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/GirvanNewmanAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/KosarajuAlgorithm.java
  src/cu/edu/cujae/graphy/core/Node.java
  src/cu/edu/cujae/graphy/core/Weight.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractEdge.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/iterators/AbstractGraphIterator.java
  src/cu/edu/cujae/graphy/core/iterators/GraphIterator.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
  src/cu/edu/cujae/graphy/math/BinaryOperation.java
  src/cu/edu/cujae/graphy/math/UnaryOperation.java
  src/cu/edu/cujae/graphy/utils/HashTuple.java
  src/cu/edu/cujae/graphy/utils/Tuple.java
  test/cu/edu/cujae/graphy/tests/CloneTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/DialAlgorithmTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/KosarajuTest.java
Labels: documentation, enhancement

#58 Revisa ><
  src/cu/edu/cujae/graphy/algorithms/FordFulkersonAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/GirvanNewmanAlgorithm.java
  src/cu/edu/cujae/graphy/core/Graph.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  test/cu/edu/cujae/graphy/tests/algorithms/DijkstraTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/FordFulkersonTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/GivanNewmanAlgorithmTest.java
Labels: bug

#60 Algoritmo KatzCentrality
  src/cu/edu/cujae/graphy/algorithms/DijkstraShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/FloydWarshall.java
  src/cu/edu/cujae/graphy/algorithms/FordFulkersonAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/IsolatedVertices.java
  src/cu/edu/cujae/graphy/algorithms/KatzCentrality.java
  src/cu/edu/cujae/graphy/core/Graph.java
  src/cu/edu/cujae/graphy/core/Node.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/core/abstractions/AdjacencyListGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultWeightedGraph.java
  src/cu/edu/cujae/graphy/core/exceptions/InvalidKeyException.java
  src/cu/edu/cujae/graphy/core/iterators/AbstractGraphIterator.java
  src/cu/edu/cujae/graphy/core/iterators/GraphIterator.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
  src/cu/edu/cujae/graphy/core/utility/Graphs.java
  src/cu/edu/cujae/graphy/utils/Matrix2d.java
  src/cu/edu/cujae/graphy/utils/Pair.java
  test/cu/edu/cujae/graphy/tests/algorithms/FloydWarshallTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/FordFulkersonTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/KatzCentralityTest.java
Labels: hotfix

#61 Mi querido algoritmo Greedy Coloring <3
  src/cu/edu/cujae/graphy/algorithms/DijkstraShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/FloydWarshall.java
  src/cu/edu/cujae/graphy/algorithms/FordFulkersonAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/GreedyColoringAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/IsolatedVertices.java
  src/cu/edu/cujae/graphy/algorithms/KatzCentrality.java
  src/cu/edu/cujae/graphy/core/Graph.java
  src/cu/edu/cujae/graphy/core/Node.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/core/abstractions/AdjacencyListGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultWeightedGraph.java
  src/cu/edu/cujae/graphy/core/exceptions/InvalidKeyException.java
  src/cu/edu/cujae/graphy/core/iterators/AbstractGraphIterator.java
  src/cu/edu/cujae/graphy/core/iterators/GraphIterator.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
  src/cu/edu/cujae/graphy/core/utility/Graphs.java
  src/cu/edu/cujae/graphy/utils/Matrix2d.java
  src/cu/edu/cujae/graphy/utils/Pair.java
  test/cu/edu/cujae/graphy/tests/algorithms/FloydWarshallTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/FordFulkersonTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/GreedyColoringTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/KatzCentralityTest.java
Labels: enhancement, good first issue, hotfix

#62 Integration of changes
  README.md
  src/cu/edu/cujae/graphy/algorithms/FordFulkersonAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/GreedyColoringAlgorithm.java
  test/cu/edu/cujae/graphy/tests/algorithms/GreedyColoringTest.java
Labels: documentation, enhancement

#64 Bugfix
  src/cu/edu/cujae/graphy/algorithms/GirvanNewmanAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/GreedyColoringAlgorithm.java
  src/cu/edu/cujae/graphy/core/abstractions/AdjacencyListGraph.java
  test/cu/edu/cujae/graphy/tests/algorithms/FloydWarshallTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/GreedyColoringTest.java
Labels: bug, hotfix

#63 Integration
  README.md
  src/cu/edu/cujae/graphy/algorithms/DijkstraShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/FloydWarshall.java
  src/cu/edu/cujae/graphy/algorithms/FordFulkersonAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/GirvanNewmanAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/GreedyColoringAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/IsolatedVertices.java
  src/cu/edu/cujae/graphy/algorithms/KatzCentrality.java
  src/cu/edu/cujae/graphy/core/Graph.java
  src/cu/edu/cujae/graphy/core/Node.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/core/abstractions/AdjacencyListGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultWeightedGraph.java
  src/cu/edu/cujae/graphy/core/exceptions/InvalidKeyException.java
  src/cu/edu/cujae/graphy/core/iterators/AbstractGraphIterator.java
  src/cu/edu/cujae/graphy/core/iterators/GraphIterator.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
  src/cu/edu/cujae/graphy/core/utility/Graphs.java
  src/cu/edu/cujae/graphy/utils/Matrix2d.java
  src/cu/edu/cujae/graphy/utils/Pair.java
  test/cu/edu/cujae/graphy/tests/algorithms/FloydWarshallTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/FordFulkersonTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/GreedyColoringTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/KatzCentralityTest.java
Labels: documentation, enhancement

#68 Code cleansing
  src/cu/edu/cujae/graphy/algorithms/BellmanFordShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/ColorableAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/DialShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/DijkstraShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/FloydWarshall.java
  src/cu/edu/cujae/graphy/algorithms/FordFulkersonAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/GreedyColoringAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/IsolatedVertices.java
  src/cu/edu/cujae/graphy/algorithms/KargerMinimumCut.java
  src/cu/edu/cujae/graphy/algorithms/KatzCentrality.java
  src/cu/edu/cujae/graphy/algorithms/KosarajuAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/MotherVertexFind.java
  src/cu/edu/cujae/graphy/algorithms/PathDetection.java
  src/cu/edu/cujae/graphy/algorithms/PrimMinimalTree.java
  src/cu/edu/cujae/graphy/core/Tree.java
  src/cu/edu/cujae/graphy/core/TreeNode.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractEdge.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractWeight.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNotDirectedEdgeFactory.java
  src/cu/edu/cujae/graphy/core/trees/AbstractTree.java
  src/cu/edu/cujae/graphy/core/trees/AbstractTreeNode.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
  src/cu/edu/cujae/graphy/utils/MapBiArray.java
  test/cu/edu/cujae/graphy/tests/LocalTest.java
  test/cu/edu/cujae/graphy/tests/TreeTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/BellmanFordTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/BridgeFinderTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/DialAlgorithmTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/FloydWarshallTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/IsolatedVerticesTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/KatzCentralityTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/KosarajuTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/PathDetectionTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/PrimTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/ShortestPathKEdgeTest.java
Labels: code cleansing

#67 Casi terminada la implementación de ColorableAlgorithm
  src/cu/edu/cujae/graphy/algorithms/ColorableAlgorithm.java
  test/cu/edu/cujae/graphy/tests/algorithms/ColorableAlgorithmTest.java
Labels: documentation, enhancement, good first issue, question

#71 Integration into development
  nbproject/project.properties
  src/cu/edu/cujae/graphy/core/Tree.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTree.java
  test/cu/edu/cujae/graphy/tests/TreeTest.java
Labels: enhancement

#74 Development césar fernández
  src/cu/edu/cujae/graphy/algorithms/EulerianCycleDetection.java
  test/cu/edu/cujae/graphy/tests/EulerianCycleDetectionTest.java
Labels: enhancement, good first issue

#75 Bugfix
  src/cu/edu/cujae/graphy/algorithms/EulerianCycleDetection.java
  src/cu/edu/cujae/graphy/core/Graph.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultSimpleGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultWeightedGraph.java
  src/cu/edu/cujae/graphy/core/utility/Graphs.java
  test/cu/edu/cujae/graphy/tests/EulerianCycleDetectionTest.java
  test/cu/edu/cujae/graphy/tests/RemovalTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/EulerianCycleDetectionTest.java
Labels: bug, hotfix

#76 Algoritmo FirstLevelCommunity
  src/cu/edu/cujae/graphy/algorithms/EulerianCycleDetection.java
  src/cu/edu/cujae/graphy/algorithms/FirstLevelCommunities.java
  src/cu/edu/cujae/graphy/algorithms/IsolatedVertices.java
  src/cu/edu/cujae/graphy/core/Graph.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultSimpleGraph.java
  src/cu/edu/cujae/graphy/core/defaults/DefaultWeightedGraph.java
  src/cu/edu/cujae/graphy/core/utility/Graphs.java
  test/cu/edu/cujae/graphy/tests/RemovalTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/EulerianCycleDetectionTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/FirstLevelCommunitiesTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/IsolatedVerticesTest.java
Labels: documentation, enhancement

#81 Development Amaya Delgado
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTree.java
Labels: enhancement

#84 javadoc mejorado ;)
  src/cu/edu/cujae/graphy/algorithms/BellmanFordShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/ColorableAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/DialShortestPath.java
  src/cu/edu/cujae/graphy/algorithms/EulerianCycleDetection.java
  src/cu/edu/cujae/graphy/algorithms/FirstLevelCommunities.java
  src/cu/edu/cujae/graphy/algorithms/FloydWarshall.java
  src/cu/edu/cujae/graphy/algorithms/FordFulkersonAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/GreedyColoringAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/KatzCentrality.java
  src/cu/edu/cujae/graphy/algorithms/KosarajuAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/PrimMinimalTree.java
Labels: documentation

#88 Development jose carlos garcia
  src/cu/edu/cujae/graphy/algorithms/KruskalMinimumSpanningTree.java
  src/cu/edu/cujae/graphy/core/Tree.java
  test/cu/edu/cujae/graphy/tests/algorithms/KruskalMinimumSpanningTreeTest.java
Labels: documentation, enhancement

#90 Karger Minimum Cut
  src/cu/edu/cujae/graphy/algorithms/AbstractAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/KargerMinimumCut.java
  src/cu/edu/cujae/graphy/core/Tree.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTree.java
  src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
  test/cu/edu/cujae/graphy/tests/TreeTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/KargerMinimumCutTest.java
Labels: enhancement

#93 Development amaya delgado
  src/cu/edu/cujae/graphy/algorithms/BiconnectivityDetection.java
  src/cu/edu/cujae/graphy/algorithms/ConnectivityDetection.java
  test/cu/edu/cujae/graphy/tests/algorithms/BiconnectivityDetectionTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/ConnectivityDetectionTest.java
Labels: documentation, enhancement

#94 Algoritmo ShortestPathUnweightedGraph <3
  src/cu/edu/cujae/graphy/algorithms/ShortestPathUnweightedGraph.java
  test/cu/edu/cujae/graphy/tests/algorithms/ShortestPathUnweightedGraphTest.java
Labels: documentation, enhancement

#100 Development amaya delgado
  src/cu/edu/cujae/graphy/algorithms/BronKerboschAlgorithm.java
  test/cu/edu/cujae/graphy/tests/algorithms/BiconnectivityDetectionTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/BronKerboschTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/ConnectivityDetectionTest.java
Labels: documentation, enhancement

#105 Hello again again <3
  src/cu/edu/cujae/graphy/algorithms/KCoresFinderAlgorithm.java
  src/cu/edu/cujae/graphy/algorithms/MaximumBipartiteMatch.java
  src/cu/edu/cujae/graphy/algorithms/MinimumVertexCoverAlgorithm.java
  src/cu/edu/cujae/graphy/core/Tree.java
  src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
  src/cu/edu/cujae/graphy/utils/MapBiArray.java
  test/cu/edu/cujae/graphy/tests/algorithms/KCoresFinderAlgorithmTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/MaximumBipartiteMatchTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/MinimumVertexCoverAlgorithmTest.java
Labels: documentation, enhancement

#101 Development jose carlos garcia
  src/cu/edu/cujae/graphy/algorithms/DynamicConnectivity.java
  src/cu/edu/cujae/graphy/algorithms/NumberCiclyesKLenght.java
  test/cu/edu/cujae/graphy/tests/algorithms/DynamicConnectivityTest.java
  test/cu/edu/cujae/graphy/tests/algorithms/NumberCiclyesKLenghtTest.java
Labels: documentation, enhancement
